// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeDose.Domain.ApplicationDbContext;

#nullable disable

namespace SafeDose.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624235149_LastReminderDate")]
    partial class LastReminderDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<byte>("AccountStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AccountStatus = (byte)0,
                            ConcurrencyStamp = "e44983c8-daf0-41d2-8da7-7ba3d458e2a6",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "superadmin",
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEF32sxBFUvoHZkUa4hVKNb+ZtKYUlJU+hkPprnsqagNcj/Tq+HpFlr6VyImmf9BNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae30ac4d-45f2-4bde-98e1-bcefba31cc89",
                            TwoFactorEnabled = false,
                            UserName = "superadmin"
                        });
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("ActionType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EntityRowId")
                        .HasColumnType("int");

                    b.Property<string>("PHIAccessReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("AccountId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.ClinicDescriptionReminder", b =>
                {
                    b.Property<int>("ClinicDescriptionReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicDescriptionReminderId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsVisit")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReminderNote")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("VisitDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ClinicDescriptionReminderId");

                    b.HasIndex("PatientId");

                    b.ToTable("ClinicDescriptionReminders");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<int>("ConsentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsentRecordId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Consent_Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.HasKey("ConsentRecordId");

                    b.HasIndex("AccountId");

                    b.ToTable("ConsentRecords");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.CriticalPair", b =>
                {
                    b.Property<int>("CriticalPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriticalPairId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("DefaultLevel")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DrugIdA")
                        .HasColumnType("int");

                    b.Property<int?>("DrugIdB")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ReasonEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ScientificNameA")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ScientificNameB")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CriticalPairId");

                    b.HasIndex("DrugIdB");

                    b.HasIndex("IsActive");

                    b.HasIndex("DrugIdA", "DrugIdB");

                    b.ToTable("CriticalPairs");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DrugCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<byte?>("Route")
                        .HasColumnType("tinyint");

                    b.HasKey("DrugId");

                    b.HasIndex("AccountId");

                    b.HasIndex("DrugCatalogId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("AccountId", "IsVerified");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.DrugCatalog", b =>
                {
                    b.Property<int>("DrugCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugCatalogId"));

                    b.Property<string>("CommercialNameAr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CommercialNameEn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DrugClass")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PriceEgp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Route")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DrugCatalogId");

                    b.HasIndex("CommercialNameAr");

                    b.HasIndex("CommercialNameEn");

                    b.HasIndex("ScientificName");

                    b.ToTable("DrugCatalogs");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.FreeTierUsage", b =>
                {
                    b.Property<int>("FreeTierUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FreeTierUsageId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InteractionCheckCount")
                        .HasColumnType("int");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("OCRCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ResetDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("VoiceInputCount")
                        .HasColumnType("int");

                    b.HasKey("FreeTierUsageId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("FreeTierUsages");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.InteractionCheck", b =>
                {
                    b.Property<int>("InteractionCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteractionCheckId"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedByAccountId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CacheKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CheckedDrugsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ConflictingPairsJson")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int?>("ConsentRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DrugCount")
                        .HasColumnType("tinyint");

                    b.Property<string>("ExplanationArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabelArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PineconeIndexVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RecommendedActionArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SafetyDisclaimerArabic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("SeverityLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TitleArabic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("TriggerType")
                        .HasColumnType("tinyint");

                    b.HasKey("InteractionCheckId");

                    b.HasIndex("AcknowledgedByAccountId");

                    b.HasIndex("CacheKey");

                    b.HasIndex("ConsentRecordId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "CheckedAt");

                    b.ToTable("InteractionChecks");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.OTPRequest", b =>
                {
                    b.Property<int>("OTPRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTPRequestId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashedCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OTPRequestId");

                    b.HasIndex("AccountId");

                    b.ToTable("OTPRequests");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ChronicConditions")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MedicalCardToken")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PatientId");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "IsActive");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PatientMedication", b =>
                {
                    b.Property<int>("PatientMedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientMedicationId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("Frequency")
                        .HasColumnType("int");

                    b.Property<byte?>("MealTiming")
                        .HasColumnType("tinyint");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("PatientMedicationId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientMedications");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PatientMedicationTime", b =>
                {
                    b.Property<int>("PatientMedicationTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientMedicationTimeId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("LastReminderDate")
                        .HasColumnType("date");

                    b.Property<int>("PatientMedicationId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("PatientMedicationTimeId");

                    b.HasIndex("PatientMedicationId");

                    b.ToTable("PatientMedicationTimes");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("GateWay")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("GateWayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("OCRStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("OCRText")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrescriptionName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("SourceType")
                        .HasColumnType("tinyint");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PricingChangeHistory", b =>
                {
                    b.Property<int>("PricingChangeHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingChangeHistoryId"));

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChangedByAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PricingTierId")
                        .HasColumnType("int");

                    b.HasKey("PricingChangeHistoryId");

                    b.HasIndex("ChangedByAccountId");

                    b.HasIndex("PricingTierId");

                    b.ToTable("PricingChangeHistories");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PricingTier", b =>
                {
                    b.Property<int>("PricingTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingTierId"));

                    b.Property<int>("BillingCycleDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("InteractionCheckLimitPerDay")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MedicationLimitPerPatient")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PatientLimit")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionParseLimit")
                        .HasColumnType("int");

                    b.Property<string>("TierCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TierNameArabic")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PricingTierId");

                    b.HasIndex("TierCode")
                        .IsUnique();

                    b.ToTable("PricingTiers");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PricingTierFeature", b =>
                {
                    b.Property<int>("PricingTierFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingTierFeatureId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("LabelArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PricingTierId")
                        .HasColumnType("int");

                    b.HasKey("PricingTierFeatureId");

                    b.HasIndex("PricingTierId");

                    b.ToTable("PricingTierFeatures");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<int>("PushSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PushSubscriptionId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("P256DH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PushSubscriptionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscription");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.ReminderResponse", b =>
                {
                    b.Property<int>("ReminderResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderResponseId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientMedicationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ResponseType")
                        .HasColumnType("tinyint");

                    b.Property<string>("TimeDrug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReminderResponseId");

                    b.HasIndex("PatientMedicationId");

                    b.ToTable("ReminderResponses");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PricingTierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PricingTierId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.SymptomReport", b =>
                {
                    b.Property<int>("SymptomReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymptomReportId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArabicExplanation")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<byte?>("ClassificationLevel")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InputType")
                        .HasColumnType("tinyint");

                    b.Property<string>("OriginalText")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RecommendationAction")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("SymptomReportId");

                    b.HasIndex("PatientId");

                    b.ToTable("SymptomReports");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeDose.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "Account")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.ClinicDescriptionReminder", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Patient", "Patient")
                        .WithMany("ClinicDescriptionReminders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "Account")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.CriticalPair", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Drug", "DrugA")
                        .WithMany()
                        .HasForeignKey("DrugIdA")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SafeDose.Domain.Entities.Drug", "DrugB")
                        .WithMany()
                        .HasForeignKey("DrugIdB")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DrugA");

                    b.Navigation("DrugB");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Drug", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.DrugCatalog", "DrugCatalog")
                        .WithMany()
                        .HasForeignKey("DrugCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SafeDose.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Drugs")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DrugCatalog");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.FreeTierUsage", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "Account")
                        .WithOne("FreeTierUsage")
                        .HasForeignKey("SafeDose.Domain.Entities.FreeTierUsage", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.InteractionCheck", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.ConsentRecord", "ConsentRecord")
                        .WithMany()
                        .HasForeignKey("ConsentRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SafeDose.Domain.Entities.Patient", "Patient")
                        .WithMany("InteractionChecks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConsentRecord");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.OTPRequest", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "Account")
                        .WithMany("OTPRequests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Patient", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "Account")
                        .WithMany("Patients")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PatientMedication", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Drug", "Drug")
                        .WithMany("PatientMedications")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeDose.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientMedications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PatientMedicationTime", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.PatientMedication", "PatientMedication")
                        .WithMany("PatientMedicationTimes")
                        .HasForeignKey("PatientMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientMedication");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PricingChangeHistory", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "ChangedByAccount")
                        .WithMany("PricingChangeHistories")
                        .HasForeignKey("ChangedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafeDose.Domain.Entities.PricingTier", "PricingTier")
                        .WithMany("PricingChangeHistories")
                        .HasForeignKey("PricingTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByAccount");

                    b.Navigation("PricingTier");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PricingTierFeature", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.PricingTier", "PricingTier")
                        .WithMany("Features")
                        .HasForeignKey("PricingTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingTier");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "Account")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.ReminderResponse", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.PatientMedication", "PatientMedication")
                        .WithMany("ReminderResponses")
                        .HasForeignKey("PatientMedicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PatientMedication");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Account", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeDose.Domain.Entities.PricingTier", "PricingTier")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PricingTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PricingTier");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.SymptomReport", b =>
                {
                    b.HasOne("SafeDose.Domain.Entities.Patient", "Patient")
                        .WithMany("SymptomReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Account", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ConsentRecords");

                    b.Navigation("FreeTierUsage");

                    b.Navigation("OTPRequests");

                    b.Navigation("Patients");

                    b.Navigation("PricingChangeHistories");

                    b.Navigation("PushSubscriptions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Drug", b =>
                {
                    b.Navigation("PatientMedications");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Patient", b =>
                {
                    b.Navigation("ClinicDescriptionReminders");

                    b.Navigation("InteractionChecks");

                    b.Navigation("PatientMedications");

                    b.Navigation("Prescriptions");

                    b.Navigation("SymptomReports");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PatientMedication", b =>
                {
                    b.Navigation("PatientMedicationTimes");

                    b.Navigation("ReminderResponses");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Drugs");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.PricingTier", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("PricingChangeHistories");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SafeDose.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
